=== 329379172/mapping4java/src/main/resources/META-INF/mapping.xsd
<?xml version="1.0" encoding="GBK"?>
<xs:schema targetNamespace="http://www.alibaba.com/schema/mapping" xmlns="http://www.alibaba.com/schema/mapping" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:element name="bean-mappings">
        <xs:annotation>
        	<xs:documentation>bean mappings config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:annotation>
            	<xs:documentation>src/target bean mapping </xs:documentation>
            </xs:annotation>
            <xs:sequence>
    			<xs:element ref="bean-mapping" maxOccurs="unbounded" />
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>

    <xs:element name="bean-mapping">
        <xs:complexType>
        	<xs:sequence>
        		<xs:element ref="field-mapping" maxOccurs="unbounded" />
        	</xs:sequence>
        	<xs:attribute name="srcClass" type="xs:string"
        		use="required" />
        	<xs:attribute name="srcKey" type="xs:string" default="src">
        		<xs:annotation>
        			<xs:documentation>script context for key, you can use define script with "srcKey.field"</xs:documentation>
        		</xs:annotation></xs:attribute>
        	<xs:attribute name="targetClass" type="xs:string"
        		use="required" />
        	<xs:attribute name="targetKey" type="xs:string" default="target">
        		<xs:annotation>
        			<xs:documentation>script context for key, you can use define script with &quot;srcKey.field&quot;</xs:documentation></xs:annotation></xs:attribute>
        	<xs:attribute name="reversable" type="xs:boolean"
        		use="optional" default="false" />
        	<xs:attribute name="batch" type="xs:boolean"
        		use="optional" default="false" />
        </xs:complexType>
    </xs:element>

    <xs:element name="field-mapping">
        <xs:complexType>
        	<xs:attribute name="srcName" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>src field name</xs:documentation>
        		</xs:annotation></xs:attribute>
        	<xs:attribute name="targetName" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>target field name</xs:documentation>
        		</xs:annotation></xs:attribute>
        	<xs:attribute name="srcClass" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>src field class</xs:documentation>
        		</xs:annotation></xs:attribute>
        	<xs:attribute name="targetClass" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>target field class</xs:documentation>
        		</xs:annotation></xs:attribute>
        	<xs:attribute name="defaultValue" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>if target value is null , defaultValue is used</xs:documentation>
        		</xs:annotation></xs:attribute>
        	<xs:attribute name="convetor" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>custom convetor alias</xs:documentation>
        		</xs:annotation></xs:attribute>
        	<xs:attribute name="script" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>format script</xs:documentation>
        		</xs:annotation></xs:attribute>
        	<xs:attribute name="mapping" type="xs:boolean" use="optional" default="false">
        		<xs:annotation>
        			<xs:documentation>nested mapping</xs:documentation>
        		</xs:annotation></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 329379172/mapping4java/src/test/resources/mapping/script-mapping.xml
<?xml version="1.0" encoding="GBK"?>
<bean-mappings xmlns="http://www.alibaba.com/schema/mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.alibaba.com/schema/mapping ../../../main/resources/META-INF/mapping.xsd">

    <!--  bean script测试, map转化到object -->
    <bean-mapping srcClass="com.agapple.mapping.object.SrcMappingObject" targetClass="map">
    	<field-mapping targetName="integerValue" script="src.integerValue" defaultValue="1"/>
    	<field-mapping targetName="intValue" script="src.intValue + target.integerValue" />
    	<field-mapping targetName="start" script="src.start"/>
    	<field-mapping targetName="name" script="src.name"/> <!--  注意不同名 -->
    	<field-mapping srcName="mapping" targetName="mapping" mapping="true" />
    </bean-mapping>
    
    <bean-mapping srcClass="com.agapple.mapping.object.NestedSrcMappingObject" targetClass="map">
    	<field-mapping targetName="name" script="src.name" defaultValue="ljh" /> <!-- 测试default value -->
    	<field-mapping targetName="value" script="src.bigDecimalValue" targetClass="string" defaultValue="10" /> <!-- 测试不同名+不同类型+default value  -->
    </bean-mapping>
    
    <bean-mapping srcClass="map" targetClass="com.agapple.mapping.object.SrcMappingObject">
    	<field-mapping targetName="integerValue" script="src.integerValue" defaultValue="1"/>
    	<field-mapping targetName="intValue" script="src.intValue + src.integerValue" />
    	<field-mapping targetName="start" script="src.start"/>
    	<field-mapping targetName="name" script="src.name"/> <!--  注意不同名 -->
    	<field-mapping srcName="mapping" targetName="mapping" mapping="true" />
    </bean-mapping>
    
    <bean-mapping srcClass="map" targetClass="com.agapple.mapping.object.NestedSrcMappingObject">
    	<field-mapping targetName="name" script="src.name" defaultValue="ljh" /> <!-- 测试default value -->
    	<field-mapping targetName="bigDecimalValue" script="src.value" targetClass="string" defaultValue="10" /> <!-- 测试不同名+不同类型+default value  -->
    </bean-mapping>
    
    <bean-mapping srcClass="map" targetClass="com.agapple.mapping.object.NestedTargetMappingObject">
    	<field-mapping targetName="name" script="src.name" defaultValue="ljh" /> <!-- 测试default value -->
    	<field-mapping targetName="value" script="src.value" targetClass="string" defaultValue="10" /> <!-- 测试不同名+不同类型+default value  -->
    </bean-mapping>
    
</bean-mappings>
